export type Channel = "email" | "sms" | "whatsapp";

export type TemplateSeed = {
  templateKey: string;
  channel: Channel;
  name: string;
  description: string;
  eventKey: string;
  variables: string[];
  subject: string;
  body: string;
  waCategory?: "AUTHENTICATION" | "UTILITY" | "MARKETING";
};

export const EVENT_KEYS = [
  "otp_issued",
  "user_welcome",
  "booking_confirmed",
  "payment_receipt",
  "consultation_reminder",
  "astrologer_approved",
  "astrologer_rejected",
  "subscription_renewal",
  "subscription_expiry",
  "abandoned_cart",
  "daily_horoscope",
] as const;

export const PRESET_TEMPLATES: TemplateSeed[] = [
  {
    templateKey: "otp_verification",
    channel: "email",
    name: "OTP / verification (email)",
    description: "Login or signup OTP.",
    eventKey: "otp_issued",
    variables: ["user_name", "otp_code", "brand_name"],
    subject: "{{brand_name}} verification code",
    body: "Hello {{user_name}},\n\nYour verification code is {{otp_code}}. It expires in 10 minutes.\n\n— {{brand_name}}",
  },
  {
    templateKey: "otp_verification",
    channel: "sms",
    name: "OTP / verification (SMS)",
    description: "Login or signup OTP SMS.",
    eventKey: "otp_issued",
    variables: ["otp_code", "brand_name"],
    subject: "",
    body: "{{brand_name}} code: {{otp_code}}. Valid 10 min. Do not share.",
  },
  {
    templateKey: "otp_verification",
    channel: "whatsapp",
    name: "OTP / verification (WhatsApp)",
    description: "Meta AUTHENTICATION template. Cannot send until approved.",
    eventKey: "otp_issued",
    variables: ["otp_code", "brand_name"],
    subject: "",
    body: "Your {{brand_name}} verification code is {{otp_code}}.",
    waCategory: "AUTHENTICATION",
  },
  {
    templateKey: "welcome",
    channel: "email",
    name: "Welcome",
    description: "New user welcome.",
    eventKey: "user_welcome",
    variables: ["user_name", "brand_name"],
    subject: "Welcome to {{brand_name}}",
    body: "Namaste {{user_name}},\n\nYour account is ready. Explore kundli, panchang, and consults on {{brand_name}}.\n\n— Team {{brand_name}}",
  },
  {
    templateKey: "booking_confirmation",
    channel: "email",
    name: "Booking confirmation",
    description: "Consultation booked.",
    eventKey: "booking_confirmed",
    variables: ["user_name", "astrologer_name", "appointment_time", "brand_name"],
    subject: "Consultation confirmed with {{astrologer_name}}",
    body: "Hello {{user_name}},\n\nYour consultation with {{astrologer_name}} is confirmed for {{appointment_time}}.\n\n— {{brand_name}}",
  },
  {
    templateKey: "booking_confirmation",
    channel: "sms",
    name: "Booking confirmation (SMS)",
    description: "Short booking SMS.",
    eventKey: "booking_confirmed",
    variables: ["astrologer_name", "appointment_time"],
    subject: "",
    body: "Consult with {{astrologer_name}} at {{appointment_time}}. See you then.",
  },
  {
    templateKey: "booking_confirmation",
    channel: "whatsapp",
    name: "Booking confirmation (WhatsApp)",
    description: "UTILITY template — Meta approval required for business-initiated send.",
    eventKey: "booking_confirmed",
    variables: ["user_name", "astrologer_name", "appointment_time"],
    subject: "",
    body: "Hello {{user_name}}, your consult with {{astrologer_name}} is confirmed at {{appointment_time}}.",
    waCategory: "UTILITY",
  },
  {
    templateKey: "payment_receipt",
    channel: "email",
    name: "Payment receipt",
    description: "GST invoice issued.",
    eventKey: "payment_receipt",
    variables: ["user_name", "invoice_no", "amount", "brand_name"],
    subject: "Receipt {{invoice_no}} from {{brand_name}}",
    body: "Hello {{user_name}},\n\nWe received {{amount}}. Tax invoice {{invoice_no}} is attached in your account.\n\n— {{brand_name}}",
  },
  {
    templateKey: "payment_receipt",
    channel: "sms",
    name: "Payment receipt (SMS)",
    description: "Payment SMS.",
    eventKey: "payment_receipt",
    variables: ["invoice_no", "amount"],
    subject: "",
    body: "Payment {{amount}} received. Invoice {{invoice_no}}.",
  },
  {
    templateKey: "consultation_reminder",
    channel: "email",
    name: "Consultation reminder",
    description: "Upcoming consult reminder.",
    eventKey: "consultation_reminder",
    variables: ["user_name", "astrologer_name", "appointment_time", "brand_name"],
    subject: "Reminder: consult with {{astrologer_name}}",
    body: "Hello {{user_name}},\n\nReminder: your consult with {{astrologer_name}} starts at {{appointment_time}}.\n\n— {{brand_name}}",
  },
  {
    templateKey: "consultation_reminder",
    channel: "whatsapp",
    name: "Consultation reminder (WhatsApp)",
    description: "UTILITY reminder. Blocked until Meta approves the template.",
    eventKey: "consultation_reminder",
    variables: ["user_name", "astrologer_name", "appointment_time"],
    subject: "",
    body: "Reminder {{user_name}}: consult with {{astrologer_name}} at {{appointment_time}}.",
    waCategory: "UTILITY",
  },
  {
    templateKey: "astrologer_approval",
    channel: "email",
    name: "Astrologer approved",
    description: "Partner application accepted.",
    eventKey: "astrologer_approved",
    variables: ["astrologer_name", "brand_name"],
    subject: "You're approved on {{brand_name}}",
    body: "Namaste {{astrologer_name}},\n\nYour partner application is approved. You can take consults on {{brand_name}}.\n\n— {{brand_name}}",
  },
  {
    templateKey: "astrologer_rejection",
    channel: "email",
    name: "Astrologer not approved",
    description: "Partner application declined.",
    eventKey: "astrologer_rejected",
    variables: ["astrologer_name", "brand_name"],
    subject: "Update on your {{brand_name}} application",
    body: "Hello {{astrologer_name}},\n\nWe could not approve your partner application at this time. Reply to this email if you have questions.\n\n— {{brand_name}}",
  },
  {
    templateKey: "subscription_renewal",
    channel: "email",
    name: "Subscription renewal",
    description: "Plan renewed.",
    eventKey: "subscription_renewal",
    variables: ["user_name", "plan_name", "amount", "brand_name"],
    subject: "{{plan_name}} renewed",
    body: "Hello {{user_name}},\n\nYour {{plan_name}} plan renewed for {{amount}}.\n\n— {{brand_name}}",
  },
  {
    templateKey: "subscription_expiry",
    channel: "email",
    name: "Subscription expiry reminder",
    description: "Sent via automation offset before expiry.",
    eventKey: "subscription_expiry",
    variables: ["user_name", "plan_name", "expiry_date", "brand_name"],
    subject: "{{plan_name}} expires on {{expiry_date}}",
    body: "Hello {{user_name}},\n\nYour {{plan_name}} plan expires on {{expiry_date}}. Renew to keep access.\n\n— {{brand_name}}",
  },
  {
    templateKey: "subscription_expiry",
    channel: "sms",
    name: "Subscription expiry (SMS)",
    description: "SMS reminder before expiry.",
    eventKey: "subscription_expiry",
    variables: ["plan_name", "expiry_date"],
    subject: "",
    body: "{{plan_name}} expires {{expiry_date}}. Renew in the app.",
  },
  {
    templateKey: "abandoned_cart",
    channel: "email",
    name: "Abandoned cart",
    description: "E-commerce reminder.",
    eventKey: "abandoned_cart",
    variables: ["user_name", "product_name", "brand_name"],
    subject: "You left {{product_name}} in your cart",
    body: "Hello {{user_name}},\n\n{{product_name}} is still in your cart on {{brand_name}}.\n\n— {{brand_name}}",
  },
  {
    templateKey: "daily_horoscope",
    channel: "email",
    name: "Daily horoscope opt-in",
    description: "Opt-in daily note. MARKETING on WhatsApp.",
    eventKey: "daily_horoscope",
    variables: ["user_name", "brand_name"],
    subject: "Your daily note from {{brand_name}}",
    body: "Hello {{user_name}},\n\nYour opted-in daily horoscope is ready on {{brand_name}}.\n\n— {{brand_name}}",
  },
  {
    templateKey: "daily_horoscope",
    channel: "whatsapp",
    name: "Daily horoscope (WhatsApp)",
    description: "MARKETING category — Meta approval required; 24h session window does not apply.",
    eventKey: "daily_horoscope",
    variables: ["user_name", "brand_name"],
    subject: "",
    body: "Hello {{user_name}}, your daily horoscope from {{brand_name}} is ready.",
    waCategory: "MARKETING",
  },
];
